### ISSUE TITLE
How to avoid direct access to huggingface

### ISSUE THREAD

**Issue by lzm2275965881** [transformer-vq/transformer_vq#2]
Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/launch.py", line 482, in <module>
    main()
  File "scripts/launch.py", line 451, in main
    train(dataset=dataset, p_train_op=train_op)
  File "scripts/launch.py", line 241, in train
    train_iter = dataset.get_iter(
  File "/home/lzm/Desktop/transformer_vq/src/transformer_vq/utils/datasets.py", line 167, in get_iter
    ds = self._get_tokenized("train", shard_by_host=False)  # never shard; small
  File "/home/lzm/Desktop/transformer_vq/src/transformer_vq/utils/datasets.py", line 117, in _get_tokenized
    ds = task.get_dataset(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/dataset_providers.py", line 1443, in get_dataset
    ds = source.get_dataset(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/dataset_providers.py", line 496, in get_dataset
    return self.tfds_dataset.load(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/utils.py", line 182, in load
    return tfds.load(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 634, in load
    dbuilder = _fetch_builder(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 489, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 186, in builder
    return huggingface_dataset_builder.builder(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py", line 381, in builder
    hf_repo_id = _from_tfds_to_hf(name)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py", line 156, in _from_tfds_to_hf
    hf_names = hf_datasets.list_datasets()
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/utils/deprecation_utils.py", line 46, in wrapper
    return deprecated_function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/inspect.py", line 80, in list_datasets
    datasets = [dataset.id for dataset in datasets]
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/inspect.py", line 80, in <listcomp>
    datasets = [dataset.id for dataset in datasets]
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1492, in list_datasets
    for item in items:
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/utils/_pagination.py", line 35, in paginate
    r = session.get(path, params=params, headers=headers)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 2a26174d-f1a3-4839-ac81-7dbba4a68b13)')
Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/lzm/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/launch.py", line 482, in <module>
    main()
  File "scripts/launch.py", line 451, in main
    train(dataset=dataset, p_train_op=train_op)
  File "scripts/launch.py", line 241, in train
    train_iter = dataset.get_iter(
  File "/home/lzm/Desktop/transformer_vq/src/transformer_vq/utils/datasets.py", line 167, in get_iter
    ds = self._get_tokenized("train", shard_by_host=False)  # never shard; small
  File "/home/lzm/Desktop/transformer_vq/src/transformer_vq/utils/datasets.py", line 117, in _get_tokenized
    ds = task.get_dataset(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/dataset_providers.py", line 1443, in get_dataset
    ds = source.get_dataset(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/dataset_providers.py", line 496, in get_dataset
    return self.tfds_dataset.load(
  File "/home/lzm/.local/lib/python3.8/site-packages/seqio/utils.py", line 182, in load
    return tfds.load(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 634, in load
    dbuilder = _fetch_builder(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 489, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 186, in builder
    return huggingface_dataset_builder.builder(
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py", line 381, in builder
    hf_repo_id = _from_tfds_to_hf(name)
  File "/home/lzm/.local/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py", line 156, in _from_tfds_to_hf
    hf_names = hf_datasets.list_datasets()
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/utils/deprecation_utils.py", line 46, in wrapper
    return deprecated_function(*args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/inspect.py", line 80, in list_datasets
    datasets = [dataset.id for dataset in datasets]
  File "/home/lzm/.local/lib/python3.8/site-packages/datasets/inspect.py", line 80, in <listcomp>
    datasets = [dataset.id for dataset in datasets]
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1492, in list_datasets
    for item in items:
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/utils/_pagination.py", line 35, in paginate
    r = session.get(path, params=params, headers=headers)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/lzm/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffab9ab7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 2a26174d-f1a3-4839-ac81-7dbba4a68b13)')

1、I would like to ask if it is possible to avoid accessing the huggingface in your code by downloading the dataset locally in advance
2、I am in an area where I cannot directly access huggingface, but I can use “clash for windows” to enable proxy access on the browser. How can I avoid directly accessing huggingface in the code and instead use the pre-downloaded dataset?
Thank you very much！！！

**Comment by pyh314** [comment]
Hello, I have met the same problem as you say. Have you solved this problem? Could you please tell me how you solve this error? Thanks！
